// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StageCraft.Data;

#nullable disable

namespace StageCraft.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250423045518_AddProductionDetails")]
    partial class AddProductionDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StageCraft.Models.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClosingDay")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsWorldPremiere")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("OpeningDay")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Playwright")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PosterImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Runtime")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShowTimeEve")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ShowTimeMat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TicketLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Productions");
                });
#pragma warning restore 612, 618
        }
    }
}
